### ISSUE TITLE
no armv7 support

### ISSUE THREAD

**Issue by samyusk** [WowWeeLabs/MiP-iOS-SDK#9]
Hi, 

Seems the updated MiP SDK framework doesn't have armv7 support.

Thanks
Sam

**Comment by ffchan** [comment]
Fixed on commit 08fb6c902d0d95c438709e11136233e75f9cdfed 
Please try again

**Comment by samyusk** [comment]
Hi, 

Seems only Miposaur SDK framework is updated with including armv7, but MiP SDK framework still doesn't have armv7.  

Thanks
Sam
